name: mysql1
version: 0.18.1
description: A library for connecting to and querying MySQL & MariaDB databases.
homepage: https://github.com/adamlofts/mysql1_dart

authors:
- Adam Lofts <adam.lofts@gmail.com>
- James Ots <code@jamesots.com>
- Faisal Abid <faisal.abid@gmail.com>
- Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  collection: ^1.1.3
  crypto: ">=0.9.2 <3.0.0"
  logging: '>=0.11.1 <0.12.0'
  pool: ^1.3.6

dev_dependencies:
  mockito: ^3.0.0
  options_file:
    git:
      url: https://github.com/ferrerj/optionsfile
      ref: faebe29
  test: ^1.3.0
  pedantic: ^1.9.0
