name: mysql1
version: 0.19.2
description: A library for connecting to and querying MySQL & MariaDB databases.
homepage: https://github.com/adamlofts/mysql1_dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  crypto: ^3.0.0
  logging: ^1.0.1
  pool: ^1.5.0

dev_dependencies:
  mocktail: ^0.1.1
  options_file:
    git:
      url: https://github.com/rxlabz/optionsfile
      ref: ca741d4
  test: ^1.16.5
  pedantic: ^1.11.0
  build_runner: ^2.1.2

