name: sqljocky
version: 0.14.1
author: James Ots <code@jamesots.com>
description: A MySQL connector
homepage: https://github.com/jamesots/sqljocky
environment:
  sdk: '>=1.11.0 <2.0.0'
documentation: http://jamesots.github.io/sqljocky/docs
dependencies:
  crypto: '>=0.9.0 <0.10.0'
  logging: '>=0.11.1 <0.12.0'
  options_file: '>=0.11.0 <0.12.0'
dev_dependencies:
  test: '>=0.12.3+9 <0.13.0'
  mockito: '>=0.10.1 <0.11.0'
  args: any
